aliases.lunar: Testing with shfmt -i 2 -ci (#156)
* aliases.lunar: Testing with shfmt -i 2 -ci

I picked this one because it's already closest to the shfmt settings
that I want to use everywhere so there aren't that many changes.

What does everyone think? Should everything look like this?

* build.lunar: Reformatted with shfmt -i 2 -ci

No code has changed. Just formatting.

* check.lunar: reformatted with shfmt -i 2 -ci

* config.lunar: reformatted with shfmt -i 2 -ci

* depends.lunar: reformatted with shfmt -i 2 -ci

* download.lunar: reformatted with shfmt -i 2 -ci

* libs/edit.lunar: reformatted with shfmt -i 2 -ci

* libs/init.lunar: reformatted with shfmt -i 2 -ci

* libs/kernel.lunar: reformatted with shfmt -i 2 -ci

* libs/locking.lunar: reformatted with shfmt -i 2 -ci

* libs/logging.lunar: reformatted with shfmt -i 2 -ci

* libs/main.lunar: reformatted with shfmt -i 2 -ci

* libs/messages.lunar: reformatted with shfmt -i 2 -ci

* libs/misc.lunar: reformatted with shfmt -i 2 -ci

* libs/modules.lunar: reformatted with shfmt -i 2 -ci

* libs/moonbase.lunar: reformatted with shfmt -i 2 -ci

* libs/optimize.lunar: reformatted with shfmt -i 2 -ci

* libs/plugins.lunar: reformatted with shfmt -i 2 -ci

* libs/prune.lunar: reformatted with shfmt -i 2 -ci

* libs/queue.lunar: reformatted with shfmt -i 2 -ci

* libs/recovery.lunar: reformatted with shfmt -i 2 -ci

* libs/sizes.lunar: reformatted with shfmt -i 2 -ci

* libs/sources.lunar: reformatted with shfmt -i 2 -ci

* libs/temp.lunar: reformatted with shfmt -i 2 -ci

* libs/tracking.lunar: reformatted with shfmt -i 2 -ci

* libs/uniqid.lunar: reformatted with shfmt -i 2 -ci

* libs/updatelog.lunar: reformatted with shfmt -i 2 -ci

* libs/useradd.lunar: reformatted with shfmt -i 2 -ci

* libs/view.lunar: reformatted with shfmt -i 2 -ci

* lget: reformatted with shfmt -i 2 -ci

* lin: reformatted with shfmt -i 2 -ci

* lrm: reformatted with shfmt -i 2 -ci

* lsh: reformatted with shfmt -i 2 -ci

* lunar: reformatted with shfmt -i 2 -ci

* lvis: reformatted with shfmt -i 2 -ci

* lvu: reformatted with shfmt -i 2 -ci

* alias.menu: reformatted with shfmt -i 2 -ci

* download.menu: reformatted with shfmt -i 2 -ci

* integrity.menu: reformatted with shfmt -i 2 -ci

* license.menu: reformatted with shfmt -i 2 -ci

* mirrors.menu: reformatted with shfmt -i 2 -ci

* bootstrap: reformatted with shfmt -i 2 -ci

* init-functions: reformatted with shfmt -i 2 -ci

* c++: reformatted with shfmt -i 2 -ci

* cc: reformatted with shfmt -i 2 -ci

* g++: reformatted with shfmt -i 2 -ci

* gcc: reformatted with shfmt -i 2 -ci

* ld: reformatted with shfmt -i 2 -ci

* make: reformatted with shfmt -i 2 -ci

* build-zpatches.plugin: reformatted with shfmt -i 2 -ci

* check-find.plugin: reformatted with shfmt -i 2 -ci

* check-ldd.plugin: reformatted with shfmt -i 2 -ci

* check-md5sum.plugin: reformatted with shfmt -i 2 -ci

* check-symlinks.plugin: reformatted with shfmt -i 2 -ci

* configd.plugin: reformatted with shfmt -i 2 -ci

* download-file.plugin: reformatted with shfmt -i 2 -ci

* download-generic.plugin: reformatted with shfmt -i 2 -ci

* optimize-wrappers.plugin: reformatted with shfmt -i 2 -ci

* postbuild-generic.plugin: reformatted with shfmt -i 2 -ci

* postbuild-sanity.plugin: reformatted with shfmt -i 2 -ci

* unpack-generic.plugin: reformatted with shfmt -i 2 -ci

* verify-md5.plugin: reformatted with shfmt -i 2 -ci

* verify-sha1.plugin: reformatted with shfmt -i 2 -ci

* verify-sha256.plugin: reformatted with shfmt -i 2 -ci

diff --git a/misc/init-functions b/misc/init-functions
--- a/misc/init-functions
+++ b/misc/init-functions
@@ -12,8 +12,8 @@
 ############################################################
 
 # we really need to do this:
-trap    ":" QUIT TSTP SEGV
-export  PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
+trap ":" QUIT TSTP SEGV
+export PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 
 #
 # work notes:
@@ -22,9 +22,9 @@ export  PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 # Need to rectify daemon-restart test and script deletion of /var/run/<prog>.pid
 # Need to assess impact of the above changes elswehere
 #
-# 
 #
-# 
+#
+#
 
 #
 # for whoever called us, we would like to know the follofing data,
@@ -62,70 +62,68 @@ export  PATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 # default_{start|stop|restart|probe|reload|status}
 #
 
-  CHKCONFIG=`grep '^# chkconfig:'   "$0" | cut -d : -f 2-2`
-CONFIGFILES=`grep '^# config:'      "$0" | cut -d : -f 2-2 | tr -d " "`
+CHKCONFIG=$(grep '^# chkconfig:' "$0" | cut -d : -f 2-2)
+CONFIGFILES=$(grep '^# config:' "$0" | cut -d : -f 2-2 | tr -d " ")
 # DESCRIPTION=`grep '^# description: ' "$0" | cut -d : -f 2-2 | tr -d " "`
-      SHORT=`grep '^# short:'       "$0" | cut -d : -f 2-2 | tr -d " "`
-    PIDFILE=`grep '^# pidfile:'     "$0" | cut -d : -f 2-2 | tr -d " "`
-    PROCESS=`grep '^# processname:' "$0" | cut -d : -f 2-2 | tr -d " "`
-    SIGSTOP=`grep '^# sigstop:'     "$0" | cut -d : -f 2-2 | tr -d " "`
-  SIGRELOAD=`grep '^# sigreload:'   "$0" | cut -d : -f 2-2 | tr -d " "`
-      RUNAS=`grep '^# runas:'       "$0" | cut -d : -f 2-2 | tr -d " "`
+SHORT=$(grep '^# short:' "$0" | cut -d : -f 2-2 | tr -d " ")
+PIDFILE=$(grep '^# pidfile:' "$0" | cut -d : -f 2-2 | tr -d " ")
+PROCESS=$(grep '^# processname:' "$0" | cut -d : -f 2-2 | tr -d " ")
+SIGSTOP=$(grep '^# sigstop:' "$0" | cut -d : -f 2-2 | tr -d " ")
+SIGRELOAD=$(grep '^# sigreload:' "$0" | cut -d : -f 2-2 | tr -d " ")
+RUNAS=$(grep '^# runas:' "$0" | cut -d : -f 2-2 | tr -d " ")
 
-get_data () {
+get_data() {
   # define these
   LINKNAME=${0##*/}
   BASENAME=${LINKNAME#*[SK][0-9][0-9]}
 
   # attempt to get these right:
-  if [ ! -z $PROCESS ] ; then
+  if [ ! -z $PROCESS ]; then
     if [ "${PROCESS:0:1}" = "/" ]; then
       PROCESS_FULL=$PROCESS
-      PROCESS_BASE=`basename $PROCESS`
+      PROCESS_BASE=$(basename $PROCESS)
     else
-      if ! which 2> /dev/null ; then 
-        PROCESS_FULL=`which $PROCESS`
-        PROCESS_BASE=`basename $PROCESS`
+      if ! which 2>/dev/null; then
+        PROCESS_FULL=$(which $PROCESS)
+        PROCESS_BASE=$(basename $PROCESS)
       else
         PROCESS=
       fi
     fi
-    [ -z $PIDFILE   ] &&   PIDFILE=/var/run/$PROCESS_BASE.pid
-    [ -z $SHORT     ] &&     SHORT=$BASENAME
-    [ -z $SIGSTOP   ] &&   SIGSTOP=TERM
+    [ -z $PIDFILE ] && PIDFILE=/var/run/$PROCESS_BASE.pid
+    [ -z $SHORT ] && SHORT=$BASENAME
+    [ -z $SIGSTOP ] && SIGSTOP=TERM
     [ -z $SIGRELOAD ] && SIGRELOAD=HUP
   fi
 
   # VITAL INFO: SERVPID
-  if [ -f "$PIDFILE" ] ; then
-    if [ -d "/proc/$(cat $PIDFILE)" ] ; then
+  if [ -f "$PIDFILE" ]; then
+    if [ -d "/proc/$(cat $PIDFILE)" ]; then
       SERVPID=$(cat "$PIDFILE")
     fi
   fi
 }
 
-
 # define the output string colors and text
-        ESC=`echo -en "\033"`
-  RESULT_OK="${ESC}[\061;32m${ESC}[70G[\040\040\040OK\040\040\040]${ESC}[m"
+ESC=$(echo -en "\033")
+RESULT_OK="${ESC}[\061;32m${ESC}[70G[\040\040\040OK\040\040\040]${ESC}[m"
 RESULT_FAIL="${ESC}[\061;31m${ESC}[70G[\040FAILED\040]${ESC}[m"
 RESULT_WARN="${ESC}[\061;33m${ESC}[70G[\040\040WARN\040\040]${ESC}[m"
 JUNK="]]]]]]"
 
-
 # Handy
-pgrep () {
-  if [ -n "$SERVPID" ] ; then
+pgrep() {
+  if [ -n "$SERVPID" ]; then
     # we will kill the daemon:
-    if [ -d /proc/$SERVPID ] ; then
+    if [ -d /proc/$SERVPID ]; then
       return 0
     else
       return 1
     fi
   else
     # where is the new daemon???
-    if [ -f "$PIDFILE" ] ; then
-      if [ -d "/proc/$(cat $PIDFILE)" ] ; then
+    if [ -f "$PIDFILE" ]; then
+      if [ -d "/proc/$(cat $PIDFILE)" ]; then
         return 0
       else
         return 255
@@ -133,12 +131,12 @@ pgrep () {
     else
       # sleep 1
       # second chance:
-      if [ -f "$PIDFILE" ] ; then
-        if [ -d "/proc/$(cat $PIDFILE)" ] ; then
+      if [ -f "$PIDFILE" ]; then
+        if [ -d "/proc/$(cat $PIDFILE)" ]; then
           return 0
         else
           return 255
-	fi
+        fi
       else
         return 255
       fi
@@ -146,13 +144,12 @@ pgrep () {
   fi
 }
 
-
-pkill () {
-  if [ -z "$SERVPID" ] ; then
+pkill() {
+  if [ -z "$SERVPID" ]; then
     return 255
   else
-    if kill -$SIGSTOP $SERVPID >& /dev/null ; then
-      if [ -f $PIDFILE ] ; then
+    if kill -$SIGSTOP $SERVPID >&/dev/null; then
+      if [ -f $PIDFILE ]; then
         rm -f $PIDFILE
       fi
       return 0
@@ -162,12 +159,11 @@ pkill () {
   fi
 }
 
-
-prload () {
-  if [ ! -f $PIDFILE ] ; then
+prload() {
+  if [ ! -f $PIDFILE ]; then
     return 255
   else
-    if kill -$SIGRELOAD $SERVPID >& /dev/null ; then
+    if kill -$SIGRELOAD $SERVPID >&/dev/null; then
       return 0
     else
       return 255
@@ -175,20 +171,18 @@ prload () {
   fi
 }
 
-
-mkpid () {
-  if [ ! -e $PIDFILE ] ; then
+mkpid() {
+  if [ ! -e $PIDFILE ]; then
     echo -n "[PID] "
-    /bin/pgrep -o -P 1 "^$PROCESS_BASE$" > $PIDFILE && return 0 || return 255
-  else 
-    return 
+    /bin/pgrep -o -P 1 "^$PROCESS_BASE$" >$PIDFILE && return 0 || return 255
+  else
+    return
   fi
 }
 
-
-pidok () {
-  if [ -e $PIDFILE ] ; then
-    if pgrep ; then 
+pidok() {
+  if [ -e $PIDFILE ]; then
+    if pgrep; then
       return 0
     else
       return 255
@@ -198,59 +192,54 @@ pidok () {
   fi
 }
 
-
-log_success_msg () {
+log_success_msg() {
   echo -e "$1 $RESULT_OK"
 }
 
-
-log_failure_msg () {
+log_failure_msg() {
   echo -e "$1 $RESULT_FAIL"
 }
 
-
-log_warning_msg () {
+log_warning_msg() {
   echo -e "$1 $RESULT_WARN"
 }
 
-
-start_process () {
+start_process() {
   if [ ! -z "$RUNAS" ]; then
     /bin/su $RUNAS -c "$PROCESS_FULL $ARGS" &&
       return 0 || return 255
   else
     $PROCESS_FULL $ARGS &&
-    return 0 || return 255
+      return 0 || return 255
   fi
 }
 
-
 # the main functions are defined as default_ so you may call these
 # directly from a script too
-default_start () {
+default_start() {
   get_data
   # start the daemon
   echo -n "Starting $SHORT: "
   # check to see if it's not already running
-  if ! pgrep ; then
+  if ! pgrep; then
     # sanity check:
-    if [ -f $PIDFILE ] ; then
+    if [ -f $PIDFILE ]; then
       rm -f $PIDFILE
     fi
     # start it up ourselves
-    if start_process ; then
+    if start_process; then
       # starup succeeded, now check if it really is running
-      if pgrep ; then
+      if pgrep; then
         echo -e $RESULT_OK
-      else 
+      else
         # here's the broken daemon case
-	mkpid
-	if pgrep ; then
-	  echo -e $RESULT_OK
-	else
+        mkpid
+        if pgrep; then
+          echo -e $RESULT_OK
+        else
           # startup failed on our side
           echo -e $RESULT_FAIL
-	fi
+        fi
       fi
     fi
   else
@@ -260,24 +249,23 @@ default_start () {
   fi
 }
 
-
-default_stop () {
+default_stop() {
   get_data
   # stop the daemon
   echo -n "Stopping $SHORT: "
-  if pgrep ; then
+  if pgrep; then
     pkill
-    for COUNT in 1 2 3 4 5 ; do
+    for COUNT in 1 2 3 4 5; do
       pgrep && pkill
       pgrep && echo -n "." && sleep 1
-      if ! pgrep ; then
+      if ! pgrep; then
         # killed OK
         [ -e $PIDFILE ] && rm $PIDFILE
         echo -e $RESULT_OK
         break
       fi
     done
-    if pgrep ; then
+    if pgrep; then
       # FAILED!
       mkpid
       echo -e "kill failed$RESULT_FAIL"
@@ -287,26 +275,24 @@ default_stop () {
   fi
 }
 
-
-default_restart () {
+default_restart() {
   get_data
   # restart ourselves
   $0 stop && $0 start
 }
 
-
-default_probe () {
+default_probe() {
   get_data
   # see if we need to reload it based on the configs
-  if [ -e $PIDFILE ] ; then
+  if [ -e $PIDFILE ]; then
     # is it really there?
-    if pidok ; then
+    if pidok; then
       # test date of config files against PID dile
       NEEDRELOAD="false"
-      for CONFIGFILE in $CONFIGFILES ; do
+      for CONFIGFILE in $CONFIGFILES; do
         [ $CONFIGFILE -nt $PIDFILE ] && NEEDRELOAD="true"
       done
-      if [ "X$NEEDRELOAD" == "Xtrue" ] ; then
+      if [ "X$NEEDRELOAD" == "Xtrue" ]; then
         # we need to reload
         $0 reload
       else
@@ -324,22 +310,21 @@ default_probe () {
   fi
 }
 
-
-default_reload () {
+default_reload() {
   get_data
   # reload it
   echo -n "Reloading $SHORT: "
-  if [ -e $PIDFILE ] ; then
+  if [ -e $PIDFILE ]; then
     # we have a pid file
     prload
     # test existence
-    if pidok ; then
+    if pidok; then
       # still running then
       touch $PIDFILE
       echo -e $RESULT_OK
     else
       # something went wrong
-      if pgrep ; then
+      if pgrep; then
         # changed PID
         mkpid
         echo -e $RESULT_OK
@@ -355,17 +340,16 @@ default_reload () {
   fi
 }
 
-
-default_status () {
+default_status() {
   get_data
   # check if it is running
   echo -n "Checking $SHORT: "
-  if pidok ; then
+  if pidok; then
     # we have a pid file and it's okay
     echo -e "$RESULT_OK"
   else
     # something went wrong
-    if pgrep ; then
+    if pgrep; then
       # changed PID
       mkpid
       echo -e "Was reloaded$RESULT_OK"
@@ -377,16 +361,15 @@ default_status () {
   fi
 }
 
-
-default_install () {
+default_install() {
   get_data
   # make the links for this file go to the right places
-  LEVELS=`echo $CHKCONFIG | cut -d ' ' -f 1`
-  LSTART=`echo $CHKCONFIG | cut -d ' ' -f 2`
-  LSTOP=`echo $CHKCONFIG | cut -d ' ' -f 3`
-  ls /etc/rc?.d/???$BASENAME > /dev/null 2>&1 &&
+  LEVELS=$(echo $CHKCONFIG | cut -d ' ' -f 1)
+  LSTART=$(echo $CHKCONFIG | cut -d ' ' -f 2)
+  LSTOP=$(echo $CHKCONFIG | cut -d ' ' -f 3)
+  ls /etc/rc?.d/???$BASENAME >/dev/null 2>&1 &&
     echo "Warning: some links already exist!"
-  for LEVEL in 0 1 2 3 4 5 6 ; do
+  for LEVEL in 0 1 2 3 4 5 6; do
     echo $LEVELS | grep -q $LEVEL && {
       # make start link
       echo ln -s ../init.d/$BASENAME /etc/rc$LEVEL.d/S$LSTART$BASENAME
@@ -399,14 +382,13 @@ default_install () {
   done
 }
 
-
-default_uninstall () {
+default_uninstall() {
   get_data
-     # remove the links for this script
-  LEVELS=`echo $CHKCONFIG | cut -d ' ' -f 1`
-  LSTART=`echo $CHKCONFIG | cut -d ' ' -f 2`
-  LSTOP=`echo $CHKCONFIG | cut -d ' ' -f 3`
-  for LEVEL in 0 1 2 3 4 5 6 ; do
+  # remove the links for this script
+  LEVELS=$(echo $CHKCONFIG | cut -d ' ' -f 1)
+  LSTART=$(echo $CHKCONFIG | cut -d ' ' -f 2)
+  LSTOP=$(echo $CHKCONFIG | cut -d ' ' -f 3)
+  for LEVEL in 0 1 2 3 4 5 6; do
     echo $LEVELS | grep -q $LEVEL && {
       # remove start link
       echo rm /etc/rc$LEVEL.d/S$LSTART$BASENAME
@@ -419,49 +401,52 @@ default_uninstall () {
       # tell me PLEASE!!!
     }
   done
-  ls /etc/rc?.d/???$BASENAME > /dev/null 2>&1 &&
+  ls /etc/rc?.d/???$BASENAME >/dev/null 2>&1 &&
     echo "Warning: some links still exist!"
 }
 
-
-default_usage () { 
+default_usage() {
   # default usage message
   echo "usage: $0 {start|stop|restart|reload|status}"
 }
-
 
 # default when no action passed
 [ -z $1 ] && ACTION=usage || ACTION=$1
 
 # and run the code
-if  set | grep -q "^$ACTION ()" ; then 
+if set | grep -q "^$ACTION ()"; then
   # do the custom function
   $ACTION $@
 else
   get_data
   # these are always available:
   case $ACTION in
-               (install) default_install   ; return ;;
-	     (uninstall) default_uninstall ; return ;;
+    install)
+      default_install
+      return
+      ;;
+    uninstall)
+      default_uninstall
+      return
+      ;;
   esac
   # double check these:
   if [ -z $PROCESS ]; then
-     echo -e "Processname is not defined!$RESULT_FAIL"
-     exit 1
+    echo -e "Processname is not defined!$RESULT_FAIL"
+    exit 1
   fi
   if [ ! -x $PROCESS_FULL ]; then
     echo -e "The executable $PROCESS_BASE does not exist!$RESULT_FAIL"
     exit 1
   fi
   # do the builtin function
-  case $ACTION in 
-    (start|start_daemon) default_start     ;;
-         (stop|killproc) default_stop      ;;
-               (restart) default_restart   ;;
-                 (probe) default_probe     ;;
-                (reload) default_reload    ;;
-                (status) default_status    ;;
-                      *) default_usage     ;;
+  case $ACTION in
+    start | start_daemon) default_start ;;
+    stop | killproc) default_stop ;;
+    restart) default_restart ;;
+    probe) default_probe ;;
+    reload) default_reload ;;
+    status) default_status ;;
+    *) default_usage ;;
   esac
 fi
-
diff --git a/prog/lin b/prog/lin
--- a/prog/lin
+++ b/prog/lin
@@ -31,8 +31,8 @@
 # That is a limitation of bash and aliases
 shopt -s expand_aliases
 
-help()	{
-  cat  <<  EOF
+help() {
+  cat <<EOF
 Lin installs single or multiple modules
 
 Example:	lin  nano hdparm sudo
@@ -58,36 +58,35 @@ Optional Parameters:
 -4  | --ipv4                    Download sources using ipv4
 -6  | --ipv6                    Download sources using ipv6
 EOF
-  exit  1
+  exit 1
 }
-
 
 main() {
   debug_msg "main ($@)"
   MODULES="$@"
 
-  if echo $MODULES | grep -qw moonbase ; then
+  if echo $MODULES | grep -qw moonbase; then
     # just update moonbase, no other modules
-    if ! lget moonbase ; then
+    if ! lget moonbase; then
       exit 1
     fi
     # remove moonbase from MODULES and continue
     MODULES=$(echo $MODULES | sed 's/moonbase//g')
-    if [ -z "$MODULES" ] ; then
+    if [ -z "$MODULES" ]; then
       return
     fi
   fi
 
-  if [ -z "$MODULES" ] ; then
+  if [ -z "$MODULES" ]; then
     message "${MESSAGE_COLOR}Nothing to do!${DEFAULT_COLOR}"
     return
   fi
 
   # different approaches for multiple modules (start up downloads first)
   # and single modules (plain install)
-  if [ -z "$SINGLE_MODULE" ] ; then
+  if [ -z "$SINGLE_MODULE" ]; then
 
-    if [ -z "$TEMP_DOWNLOAD_PIDS" ] ; then
+    if [ -z "$TEMP_DOWNLOAD_PIDS" ]; then
       export TEMP_DOWNLOAD_PIDS=$(temp_create "download-pids")
       export TEMP_PREPAREDDEPS=$(temp_create "prepared-depends")
     fi
@@ -95,7 +94,7 @@ main() {
 
     # pass 1 : run full dependency checking
     # This pass does configuration and dependency identification.
-    if ! DEPS_ONLY=--deps build_depends $MODULES ; then
+    if ! DEPS_ONLY=--deps build_depends $MODULES; then
       temp_destroy $TEMP_DOWNLOAD_PIDS
       temp_destroy $TEMP_PREPAREDDEPS
       temp_destroy $TEMP_CONFIGOPTS
@@ -105,7 +104,7 @@ main() {
 
     # pass 2 : hit the download manager button and grab a beer
     # this runs as a background process, so we are off to step #3 right away
-    if [ -z "$DEPS_ONLY" ] ; then
+    if [ -z "$DEPS_ONLY" ]; then
       verbose_msg "Spawning download manager"
 
       # this code hurts more than it helps - it can stall forever (minutes)
@@ -116,33 +115,33 @@ main() {
 
       verbose_msg "download queue: $LIST $MODULES"
       for M in $LIST $MODULES; do
-          THIS_TEMP=$(temp_create "$M.download.log")
-          rm $THIS_TEMP
-          SAFE_M=$(echo $M | md5sum | awk '{print $1}')
-          eval TEMP_DOWNLOAD_LOG_$SAFE_M=$THIS_TEMP
+        THIS_TEMP=$(temp_create "$M.download.log")
+        rm $THIS_TEMP
+        SAFE_M=$(echo $M | md5sum | awk '{print $1}')
+        eval TEMP_DOWNLOAD_LOG_$SAFE_M=$THIS_TEMP
       done
       (
-          for M in $LIST $MODULES; do
-              SAFE_M=$(echo $M | md5sum | awk '{print $1}')
-              eval THIS_TEMP=\$TEMP_DOWNLOAD_LOG_$SAFE_M
-              lget $M > $THIS_TEMP 2>&1 &
-              echo "$M:`jobs -p`:$THIS_TEMP" >> $TEMP_DOWNLOAD_PIDS
-              wait
-          done
+        for M in $LIST $MODULES; do
+          SAFE_M=$(echo $M | md5sum | awk '{print $1}')
+          eval THIS_TEMP=\$TEMP_DOWNLOAD_LOG_$SAFE_M
+          lget $M >$THIS_TEMP 2>&1 &
+          echo "$M:$(jobs -p):$THIS_TEMP" >>$TEMP_DOWNLOAD_PIDS
+          wait
+        done
       ) &
 
       # pass 3 : compile/install
       # no strange stuff should happen here anymore
-      for MODULE in $MODULES ; do
-        if ! module_installed $MODULE || [ ! -n "$PROBE" ] || ( [ -n "$PROBE" ] && [ "$PROBE_EXPIRED" == "on" ] && module_is_expired $MODULE ) ; then
+      for MODULE in $MODULES; do
+        if ! module_installed $MODULE || [ ! -n "$PROBE" ] || ([ -n "$PROBE" ] && [ "$PROBE_EXPIRED" == "on" ] && module_is_expired $MODULE); then
           # 3 more conditions to stop processing this module:
-          if module_held $MODULE ; then
+          if module_held $MODULE; then
             error_message "${LRM_COLOR}Notice:${DEFAULT_COLOR}${MESSAGE_COLOR} Skipping compile and install for held module ${MODULE_COLOR}$MODULE${DEFAULT_COLOR}"
             continue
-          elif module_exiled $MODULE ; then
+          elif module_exiled $MODULE; then
             error_message "${LRM_COLOR}Notice:${DEFAULT_COLOR}${MESSAGE_COLOR} Skipping compile and install for exiled module ${MODULE_COLOR}$MODULE${DEFAULT_COLOR}"
             continue
-          elif ! module_license_accepted $MODULE ; then
+          elif ! module_license_accepted $MODULE; then
             error_message "${LRM_COLOR}Notice:${DEFAULT_COLOR}${MESSAGE_COLOR} The license of module ${MODULE_COLOR}$MODULE${DEFAULT_COLOR}${MESSAGE_COLOR} is incompatible with the list of"
             error_message "allowed and/or rejected licenses. Please adjust the ACCEPTED_LICENSES or"
             error_message "REJECTED_LICENSES variables to include or not include the specific"
@@ -152,14 +151,14 @@ main() {
             # we're good now, start installing
             linING="/var/lock/installing.$MODULE"
             verbose_msg "starting lin \"$MODULE\""
-            if ! ( SINGLE_MODULE=1 main $MODULE ) ; then
-              if [ -e "$TMP_LIN_FAIL" ] ; then
-                echo "$MODULE" >> $TMP_LIN_FAIL
+            if ! (SINGLE_MODULE=1 main $MODULE); then
+              if [ -e "$TMP_LIN_FAIL" ]; then
+                echo "$MODULE" >>$TMP_LIN_FAIL
               fi
-              lin_EXIT_STATUS=1;
+              lin_EXIT_STATUS=1
             else
-              if [ -e "$TMP_LIN_SUCCESS" ] ; then
-                echo "$MODULE" >> $TMP_LIN_SUCCESS
+              if [ -e "$TMP_LIN_SUCCESS" ]; then
+                echo "$MODULE" >>$TMP_LIN_SUCCESS
               fi
             fi
           fi
@@ -179,7 +178,7 @@ main() {
     MODULE=$MODULES
     unset RECONFIGURE
 
-    if [ -z "$TEMP_DOWNLOAD_PIDS" ] ; then
+    if [ -z "$TEMP_DOWNLOAD_PIDS" ]; then
       export TEMP_DOWNLOAD_PIDS=$(temp_create "download-pids")
       export TEMP_PREPAREDDEPS=$(temp_create "prepared-depends")
       export TEMP_CONFIGOPTS=$(temp_create "configopts")
@@ -187,42 +186,42 @@ main() {
     fi
 
     run_details $MODULE &&
-    run_depends $MODULE &&
-    WANT_VERSION= satisfy_depends $MODULE
+      run_depends $MODULE &&
+      WANT_VERSION= satisfy_depends $MODULE
 
-    if [ -z "$DEPS_ONLY" ] ; then
-      if ! module_held $MODULE ; then
-        if [ -n "$PROBE" ] ; then
+    if [ -z "$DEPS_ONLY" ]; then
+      if ! module_held $MODULE; then
+        if [ -n "$PROBE" ]; then
           # --probe install
-          if ! module_installed $MODULE ; then
-            if ! lin_module $MODULE ; then
+          if ! module_installed $MODULE; then
+            if ! lin_module $MODULE; then
               temp_destroy $TEMP_PREPAREDDEPS
-	      if [ -n "$CLEAN_TEMP" ] ; then
-	        temp_destroy $TEMP_DOWNLOAD_PIDS
-	        temp_destroy $TEMP_CONFIGOPTS
-	      fi
+              if [ -n "$CLEAN_TEMP" ]; then
+                temp_destroy $TEMP_DOWNLOAD_PIDS
+                temp_destroy $TEMP_CONFIGOPTS
+              fi
               exit 1
             fi
-          elif [ "$PROBE_EXPIRED" == "on" ] && module_is_expired $MODULE ; then
+          elif [ "$PROBE_EXPIRED" == "on" ] && module_is_expired $MODULE; then
             # probe install where module is expired
             verbose_msg "module \"$MODULE\" needs to be updated"
-            if ! SINGLE_MODULE= lin_module $MODULE ; then
+            if ! SINGLE_MODULE= lin_module $MODULE; then
               temp_destroy $TEMP_PREPAREDDEPS
-	      if [ -n "$CLEAN_TEMP" ] ; then
-		temp_destroy $TEMP_DOWNLOAD_PIDS
-		temp_destroy $TEMP_CONFIGOPTS
-	      fi
+              if [ -n "$CLEAN_TEMP" ]; then
+                temp_destroy $TEMP_DOWNLOAD_PIDS
+                temp_destroy $TEMP_CONFIGOPTS
+              fi
               exit 1
             fi
           fi
         else
           # normal install - not probed
-          if ! lin_module $MODULE ; then
+          if ! lin_module $MODULE; then
             temp_destroy $TEMP_PREPAREDDEPS
-	    if [ -n "$CLEAN_TEMP" ] ; then
-	      temp_destroy $TEMP_DOWNLOAD_PIDS
-	      temp_destroy $TEMP_CONFIGOPTS
-	    fi
+            if [ -n "$CLEAN_TEMP" ]; then
+              temp_destroy $TEMP_DOWNLOAD_PIDS
+              temp_destroy $TEMP_CONFIGOPTS
+            fi
             exit 1
           fi
         fi
@@ -230,14 +229,13 @@ main() {
         verbose_msg "Skipping held module \"$MODULE\""
       fi
     fi
-    if [ -n "$CLEAN_TEMP" ] ; then
+    if [ -n "$CLEAN_TEMP" ]; then
       temp_destroy $TEMP_DOWNLOAD_PIDS
       temp_destroy $TEMP_PREPAREDDEPS
       temp_destroy $TEMP_CONFIGOPTS
     fi
   fi
 }
-
 
 . /etc/lunar/config
 . $BOOTSTRAP
@@ -248,44 +246,94 @@ GETOPT_ARGS=$(getopt -q -n lin -o "cdgf:hprRsvV:w:46" -l "compile,debug,deps,dow
 # happens:
 trap "rm -f $(eval echo \$TEMP_PREPAREDDEPS \$TEMP_DOWNLOAD_PIDS \$INSTALLWATCHFILE) ; exit 1" INT TERM
 
-if [ -z "$?" ] ; then
+if [ -z "$?" ]; then
   help | view_file
   exit
 else
   eval set -- $GETOPT_ARGS
   export IFS="$STANDARD_IFS"
- 
+
   root_check
   enviro_check
   set_priority
- 
-  while true ; do
+
+  while true; do
     case "$1" in
-      -c|--compile     ) export COMPILE="$1" ;                      shift   ;;
-      -d|--debug       ) (( LUNAR_DEBUG++ )) ; export LUNAR_DEBUG ; shift   ;;
-         --deps        ) export DEPS_ONLY="$1" ;                    shift   ;;
-      -g|--download    ) export DOWNLOAD_ONLY="$1" ;                shift   ;;
-      -f|--from        ) export SOURCE_CACHE=$2 ;                   shift 2 ;;
-      -h|--help        ) help ; exit                                        ;;
-         --opts        ) export PASS_OPTS="$2" ;                    shift 2 ;;
-      -p|--probe       ) export PROBE="$1" ;                        shift   ;;
-      -r|--reconfigure ) export RECONFIGURE="$1" ;                  shift   ;;
-      -R|--resurrect   ) export RESURRECT="$1" ;                    shift   ;;
-      -s|--silent      ) export SILENT="$1" ;                       shift   ;;
-      -v|--verbose     ) export VERBOSE="on" ;                      shift   ;;
-      -w|--want        ) export WANT_VERSION=$2 ;                   shift 2 ;;
-      -4|--ipv4        ) export USE_IPV46=4 ;                       shift   ;;
-      -6|--ipv6        ) export USE_IPV46=6 ;                       shift   ;;
-      --) shift ; break ;;
-      *) help ; break ;;
+      -c | --compile)
+        export COMPILE="$1"
+        shift
+        ;;
+      -d | --debug)
+        ((LUNAR_DEBUG++))
+        export LUNAR_DEBUG
+        shift
+        ;;
+      --deps)
+        export DEPS_ONLY="$1"
+        shift
+        ;;
+      -g | --download)
+        export DOWNLOAD_ONLY="$1"
+        shift
+        ;;
+      -f | --from)
+        export SOURCE_CACHE=$2
+        shift 2
+        ;;
+      -h | --help)
+        help
+        exit
+        ;;
+      --opts)
+        export PASS_OPTS="$2"
+        shift 2
+        ;;
+      -p | --probe)
+        export PROBE="$1"
+        shift
+        ;;
+      -r | --reconfigure)
+        export RECONFIGURE="$1"
+        shift
+        ;;
+      -R | --resurrect)
+        export RESURRECT="$1"
+        shift
+        ;;
+      -s | --silent)
+        export SILENT="$1"
+        shift
+        ;;
+      -v | --verbose)
+        export VERBOSE="on"
+        shift
+        ;;
+      -w | --want)
+        export WANT_VERSION=$2
+        shift 2
+        ;;
+      -4 | --ipv4)
+        export USE_IPV46=4
+        shift
+        ;;
+      -6 | --ipv6)
+        export USE_IPV46=6
+        shift
+        ;;
+      --)
+        shift
+        break
+        ;;
+      *)
+        help
+        break
+        ;;
     esac
   done
 
-  if [ -n "$RESURRECT" ] ; then
+  if [ -n "$RESURRECT" ]; then
     resurrect_modules $@
   else
     main $@
   fi
 fi
-
-
