Full sync with theedge: - zlocal folders may be empty and have module names (ignored from now) - lvu submit POST method code - lvu new template code - mirror updates - config_opts code fixes - man page updates

diff --git a/bin/lvu b/bin/lvu
--- a/bin/lvu
+++ b/bin/lvu
@@ -80,6 +80,7 @@ urls        [module]       display all URLs for a module
 maintainer  module         display maintainer for a module
 version     module         display version of module in moonbase
 
+new         module         attempt to create a new module from scratch
 edit        module         copy a module to zlocal for editing
 diff        module         view changes on edited module
 submit      module         attempt to submit a module to the lunar ML
@@ -749,20 +750,23 @@ diff_module() {
     message "diff requires a single module name"
     exit 1
   fi
-  if ! run_details "$1" ; then
-      message "diff requires an existing module"
+  if ! run_details $1 ; then
+    message "diff requires an existing zlocal module"
       exit 1
-  else
-    if echo $SECTION | grep -q '^zlocal' ; then
-      ZLOCAL_OVERRIDES=off NZSECTION=$(find_section $1)
-      if echo $NZSECTION | grep -q '^zlocal' ; then
-        unset SECTION
       fi
-    else
-      message "no local copy of \"$MODULE\" exists"
+  if ! echo $SECTION | grep -q zlocal ; then
+    message "$1 is not a zlocal module, cannot diff"
       exit 1
     fi
-    ZSECTION=$(echo "$SECTION/" | sed 's/^zlocal\///g;s/\/$//')
+  NZSECTION=$(ZLOCAL_OVERRIDES=off find_section $1)
+  if [ "$SECTION" == "$NZSECTION" ] ; then
+    # new module
+    SECTION=zbeta
+    echo diff /dev/null b/zbeta/$MODULE
+    diff -Nur /var/empty $MOONBASE/zlocal/$ZSECTION/$MODULE --exclude ".svn" --exclude "CVS" | \
+    grep -v ^diff | sed "s:/var/empty/:a/zbeta/$MODULE/:g;s:$MOONBASE/zlocal/$ZSECTION/:b/zbeta/:g"
+  else
+    # modified module
     echo diff a/$NZSECTION/$MODULE b/$NZSECTION/$MODULE
     diff -Nur $MOONBASE/$NZSECTION/$MODULE $MOONBASE/zlocal/$ZSECTION/$MODULE --exclude ".svn" --exclude "CVS" | \
     grep -v ^diff | sed "s:$MOONBASE/$NZSECTION/:a/$NZSECTION/:g;s:$MOONBASE/zlocal/$ZSECTION/:b/$NZSECTION/:g"
@@ -782,8 +786,12 @@ submit_module() {
     message "submit requires a single module name."
     exit 1
   fi
-  if [ ! -x /usr/sbin/sendmail ]; then
-    message "submit requires /usr/sbin/sendmail from (postfix, exim, sendmail)"
+  if [ ! -x /usr/bin/curl ]; then
+    message "submit requires curl, please \`lin curl\`"
+    exit 1
+  fi
+  if [ -z "$ADMIN" -o "$ADMIN" == "$USER" ]; then
+    message "Please set ADMIN to your e-mail address: lunar set ADMIN \"me@my.mail.domain\""
     exit 1
   fi
   if ! run_details "$1" ; then
@@ -802,78 +810,32 @@ submit_module() {
 	  exit 1
     fi
     TMP_MSG=$(temp_create "submission")
-	BOUNDARY="===============$(date -u +%s)=="
     (
-      echo '# MODULE SUBMISSION TEMPLATE'
-      echo '# --------------------------'
-      echo '# '
-      echo '# (all lines starting with # will be deleted before sending)'
-      echo '# Please fill in the fields as complete as possible to help'
-      echo '# developers track the status of your module'
-      echo '# '
-      echo '# PLEASE DO NOT CHANGE THE FOLLOWING FIELDS:'
-      echo 'To: lunar@lunar-linux.org'
-      echo 'Date:' $(date -u -R)
-      echo 'Subject: Module submission -' $MODULE
-	  echo 'MIME-Version: 1.0'
-	  echo "Content-Type: multipart/mixed; boundary=\"$BOUNDARY\""
-      echo '# '
-      echo '# YOUR E_MAIL ADDRESS MUST BE VALID:'
-      echo 'From: '
-      echo '#Reply-To:'
-      echo '#Cc: '
-	  echo ''
-	  echo "--$BOUNDARY"
-	  echo 'Content-Type: text/plain; charset="us-ascii"'
-	  echo 'MIME-Version: 1.0'
-	  echo 'Content-Transfer-Encoding: 7bit'
-	  echo ''
-      echo '# PLEASE DO NOT CHANGE WHITESPACE ABOVE THIS LINE'
-      echo ''
-      echo '# '
-      echo '# Please fill in some of the following information if applicable:'
-      echo '# '
-      echo 'module name       :' $MODULE
-      echo 'suggested section :' $SECTION
-      echo 'update (y/n)      : n'
-      echo 'bugfix (y/n)      : n'
-      echo 'security (y/n)    : n'
-      echo ''
-      echo '# '
-      echo '# Add additional information, hints, comments below here,'
-      echo '# if you entered "y" in one of the fields above, please explain!'
-      echo '# '
-      echo ''
-      echo '# YOUR NAME HERE'
-	  echo "$USER"
-	  echo ''
-      echo '# '
-      echo '# Below is your module. Please do not change the format'
-      echo '# '
-	  echo ''
-	  echo "--$BOUNDARY"
-	  echo "Content-Type: text/plain; name=\"$1.patch\""
-	  echo 'MIME-Version: 1.0'
-	  echo ''
-	  if [ -n "$SECTION" ]; then
-	    diff -Nurb $MOONBASE/$SECTION/$MODULE $MOONBASE/zlocal/$MODULE --exclude ".svn" --exclude "CVS" | sed "s|^\([+-][+-][+-] \)$MOONBASE/[^/]*/|\1|g" | grep -v "^diff "
-	  else
-	    diff -Nurb $MOONBASE/zlocal/.nonexistant $MOONBASE/zlocal/$MODULE --exclude ".svn" --exclude "CVS" | sed "s|^\([+-][+-][+-] \)$MOONBASE/[^/]*/|\1|g" | sed "s|\.nonexistant|$MODULE|g" | grep -v "^diff "
-	  fi
-	  echo -e "\n--$BOUNDARY"
-	  echo 'Content-Type: text/plain; charset="us-ascii"'
-	  echo 'MIME-Version: 1.0'
-	  echo 'Content-Transfer-Encoding: 7bit'
-	  echo ''
-	  echo "lvu submit $1 $(cat /bin/lvu | md5sum)"
-	  echo "$(uname -r) $(if [ -f /usr/include/linux/version.h ]; then grep UTS_RELEASE /usr/include/linux/version.h | cut -d '"' -f2 ; else echo "unknown" ; fi) gcc-$(installed_version gcc) glibc-$(installed_version glibc)"
-	  echo ''
+      echo ""
+      echo "# type a changelog message here"
+      echo "# all lines starting with '#' will be removed"
     ) > $TMP_MSG
     edit_file $TMP_MSG
-    cat $TMP_MSG | grep -v '^#'
+    sed -i '/^#/d' $TMP_MSG
+    (
+      echo ''
+      echo '---'
+      echo 'from:' $ADMIN
+      echo 'module:' $1
+      echo "id: $UNIQID"
+      echo "lvu submit: $1"
+      echo "lvu: $(cat /bin/lvu | md5sum)"
+      echo "uname -r: $(uname -r)"
+      echo "kernel headers: $(if [ -f /usr/include/linux/version.h ]; then grep UTS_RELEASE /usr/include/linux/version.h | cut -d '"' -f2 ; else echo "unknown" ; fi)"
+      echo "gcc: $(installed_version gcc)"
+      echo "glibc: $(installed_version glibc)"
+      echo ''
+      echo '---'
+      lvu diff $1
+    ) >> $TMP_MSG
+    cat $TMP_MSG
     if query "Submit this module now?" y; then
-      RECIPIENT=$(grep -m 1 '^To: ' $TMP_MSG | sed 's/^To: //')
-      cat $TMP_MSG | grep -v '^#' | sendmail $RECIPIENT
+      curl -F file=@$TMP_MSG -F module=$1 -F id=$UNIQID "http://lunar-linux.org/submit.php"
       temp_destroy $TMP_MSG
     else
       message "Submission aborted. your submission was saved as $TMP_MSG"
@@ -920,6 +882,93 @@ unedit_module()
 	fi
 }
 
+
+new_module()
+{
+	if [ -z "$1" ]; then
+		echo "You have to give it a name - use \`lvu new $name\`"
+		exit 1
+	elif run_details $1 > /dev/null 2>&1 ; then
+		echo "Module \"$1\" already exists, use \`lvu edit $1\` instead"
+		exit 1
+	fi
+
+	MODULE=$1
+
+	message "Paste the principal download URL for your application:"
+	read URL
+	echo
+
+	message "Write a 1-line summary of the module. do NOT write something"
+	message "like \"foo is a...\". Write something that describes it best:"
+	read SHORT
+	echo
+
+	message "Paste the main website URL:"
+	read WEB_SITE
+	echo
+
+	LONG=$(temp_create "lvu.new.$1")
+	message "Paste 1 or 2 paragraphs of text that give a good description for $1:"
+	message "Press CONTROL-D on an empty line when finished"
+	cat - > $LONG
+
+	ENTERED=$(date +%Y%m%d)
+	UPDATED=$(date +%Y%m%d)
+
+	SOURCE_URL="$(dirname $URL)/"		# get url
+	SOURCE=$(basename $URL)			# get base
+
+	if [ ! -f $SOURCE_CACHE/$SOURCE ] ; then
+		if ! download_url $SOURCE_URL $SOURCE $SOURCE_CACHE ; then
+			echo "Unable to download $URL"
+			exit 1
+		fi
+	fi
+
+	SHA1=$(sha1sum $SOURCE_CACHE/$SOURCE | cut -c1-40)
+
+	VERSION=$(echo $SOURCE | sed "s/$MODULE//")
+	VERSION=$(echo $VERSION | sed 's/^[-]//;s/^_//')
+	VERSION=${VERSION/^_}
+	VERSION=${VERSION/.tar}
+	VERSION=${VERSION/.tgz}
+	VERSION=${VERSION/.bz2}
+	VERSION=${VERSION/.gz}
+
+	SOURCE=$(echo $SOURCE | sed "s/$MODULE/\${MODULE}/")
+	SOURCE=$(echo $SOURCE | sed "s/$VERSION/\${VERSION}/")
+
+	if ! mkdir $MOONBASE/zlocal/$1 ; then
+		message "Unable to create module folder in zlocal section"
+		exit 1
+	fi
+	(
+		cat <<EOFDETA
+          MODULE=$MODULE
+         VERSION=$VERSION
+          SOURCE=$SOURCE
+      SOURCE_URL=$SOURCE_URL
+EOFDETA
+		if [ "$(tar tf $SOURCE_CACHE/$(basename $URL) | head -n 1)" != "$MODULE-$VERSION/" ]; then
+			echo "SOURCE_DIRECTORY=\$BUILD_DIRECTORY/\$MODULE-\$VERSION"
+		fi
+		cat <<EOFDETB
+      SOURCE_VFY=sha1:$SHA1
+        WEB_SITE="$WEB_SITE"
+         ENTERED=$ENTERED
+         UPDATED=$UPDATED
+           SHORT="$SHORT"
+cat <<EOF
+EOFDETB
+		cat $LONG | fmt -72
+		echo "EOF"
+	) > $MOONBASE/zlocal/$1/DETAILS
+
+	message "Module \"$1\" created best-effort. You might have to \`lvu edit $1\" to make it work"
+	message "Don't forget to create a DEPENDS file! (hint: use \`lvu links $1\`)"
+	message "Don't forget to \`lvu submit $1\` if you think this module is useful to others!"
+}
 
 main()  {
   case $1 in
@@ -1309,6 +1358,9 @@ main()  {
    unedit)
      unedit_module $2
 	 ;;
+   new)
+     new_module $2
+     ;;
 
    *)
      help
@@ -1345,6 +1397,4 @@ else
 
   main $@
 fi
-
-
 
