syncing up lunar with theedge to keep it in time with the ISO releases

diff --git a/sbin/lin b/sbin/lin
--- a/sbin/lin
+++ b/sbin/lin
@@ -100,6 +100,10 @@ gcc_checklist() {
          touch /var/state/lunar/gcc.$PLATFORM
       fi
    fi
+   if [ "$GCCWRAPPERS" == "on" ] ; then
+     export PATH=/var/lib/lunar/compilers:${PATH}
+   fi
+   
 }
 
 run_conflicts() {
@@ -126,18 +130,19 @@ use_xinetd()  { (
   if  [  -d  $SCRIPT_DIRECTORY/xinetd.d  ]  &&
       !  grep  -q  "SERVICES="  $MODULE_CONFIG
   then
-    ALL_SERVICES=`cat  $SCRIPT_DIRECTORY/xinetd.d/*  |
-                  grep  "service"                    |
+    ALL_SERVICES=`cat  $SCRIPT_DIRECTORY/xinetd.d/[!CVS]*  |
+                  grep  "service"                          |
                   sed   "s/service //"`
 
     for  SERVICE  in  $ALL_SERVICES;  do
       if    query  "Invoke $SERVICE via xinetd?"  y
       then  SERVICES="$SERVICE $SERVICES"
+      else return 1
       fi
     done
 
     for  SERVICE  in  $SERVICES;  do
-      for  FILE  in  `ls  $SCRIPT_DIRECTORY/xinetd.d/*`;  do
+      for  FILE  in  `ls  $SCRIPT_DIRECTORY/xinetd.d/[!CVS]*`;  do
 
          if  grep  -q   "service $SERVICE"  $FILE   &&
              grep  -q   "stunnel"           $FILE;  then
@@ -148,22 +153,28 @@ use_xinetd()  { (
 
     if    [  -n  "$SERVICES"  ]
     then  add_depends  "$MODULE"  "xinetd"  "on"   "optional"
-    else  add_depends  "$MODULE"  "xinetd"  "off"  "optional"
+    else  
+       add_depends  "$MODULE"  "xinetd"  "off"  "optional"
     fi
 
     echo  "SERVICES=\"$SERVICES\""  >>  $MODULE_CONFIG
-
+    return 0
+    else
+       return 1
   fi
 ) }
+
 use_initd()  { (
-  if  [  -d  $SCRIPT_DIRECTORY/init.d  ]
-  then
-    INITDSCRIPTS=`grep -l "# chkconfig: " $SCRIPT_DIRECTORY/init.d/* | cut -d / -f 9`
+
+  if  [  -d  $SCRIPT_DIRECTORY/init.d  ] ; then
+    cd $SCRIPT_DIRECTORY/init.d
+    SCRIPTS=$(find . -type f -maxdepth 1 )
+    INITDSCRIPTS=$(grep -l "# chkconfig: " $SCRIPTS | cut -d/ -f2)
 
     for  INITDSCRIPT  in  $INITDSCRIPTS;  do
       if    query  "Invoke $INITDSCRIPT via init.d automatically at boot ?"  y
       then
-	INSTALLED_INIDSCRIPTS="$INSTALLED_INIDSCRIPTS $INITDSCRIPT"
+	INSTALLED_INIDSCRIPTS=$(echo $INSTALLED_INIDSCRIPTS $INITDSCRIPT)
       else
         if [ -f /etc/init.d/$INITDSCRIPT ] ;
 	then
@@ -173,10 +184,13 @@ use_initd()  { (
 	fi
       fi
     done
+    cd $SCRIPT_DIRECTORY
 
     echo   "INITDSCRIPTS=\"$INSTALLED_INIDSCRIPTS\"" >> $MODULE_CONFIG
   fi
+
 ) }
+
 run_configure() {
   if  [  -n  "$RECONFIGURE"  ];  then
     rm  -f  $DEPENDS_CONFIG/$MODULE
@@ -184,10 +198,11 @@ run_configure() {
   fi
 
   prepare_module_config
-  use_xinetd
+  use_xinetd || {
   if  [  -n  "$RECONFIGURE" ] || ! grep -q INITDSCRIPTS $MODULE_CONFIG ;  then
     use_initd
   fi
+  }
 
   grep -q "^"$MODULE"\$" $PREPD 2>/dev/null && return 0
 
@@ -788,24 +803,23 @@ current_locked()  {
 lin_modules()  {
   for  MODULE  in  $MODULES;  do
   
-    if [ -n "$PROBE" ] ; then
-      module_installed $MODULE && continue
-    fi
+    if ! module_installed $MODULE || [ ! -n "$PROBE" ] ; then
 
-    linING="/var/lock/installing.$MODULE"
+      linING="/var/lock/installing.$MODULE"
 
-    if  [  -n  "$COMPILE"      ]  ||
-        [  -n  "$RECONFIGURE"  ]  ||
-        module_installed  $MODULE   ||
-        !  resurrect     $MODULE;  then
-      if  !  lin_module;  then
-        if  [  -n  "$LOGTMP"  ];  then
-          echo  "$MODULE"  >>  /tmp/fail_$LOGTMP
-        fi
-        lin_EXIT_STATUS=1;  
-      else
-        if  [  -n  "$LOGTMP"  ];  then
-          echo  "$MODULE"  >>  /tmp/success_$LOGTMP
+      if  [  -n  "$COMPILE"      ]  ||
+          [  -n  "$RECONFIGURE"  ]  ||
+          module_installed  $MODULE   ||
+          !  resurrect     $MODULE;  then
+        if  !  lin_module;  then
+          if  [  -n  "$LOGTMP"  ];  then
+            echo  "$MODULE"  >>  /tmp/fail_$LOGTMP
+          fi
+          lin_EXIT_STATUS=1;  
+        else
+          if  [  -n  "$LOGTMP"  ];  then
+            echo  "$MODULE"  >>  /tmp/success_$LOGTMP
+          fi
         fi
       fi
     fi
@@ -831,16 +845,14 @@ run_lget()  {
 build_depends()  {
 
   for  MODULE  in  $MODULES;  do
-    ( 
-      if [ -n "$PROBE" ] ; then
-        module_installed $MODULE && continue
-      fi
-      
-      run_details    &&
-      run_configure  &&
-      run_depends    &&
-      satisfy_depends
-    )
+    if ! module_installed $MODULE || [ ! -n "$PROBE" ] ; then
+      ( 
+        run_details    &&
+        run_configure  &&
+        run_depends    &&
+        satisfy_depends
+      )
+    fi
   done
 
 }
@@ -852,15 +864,13 @@ pass_one()  {
 }
 build_sources()  {
   for  MODULE  in  $MODULES;  do
-    (
-      if [ -n "$PROBE" ] ; then
-        module_installed $MODULE && continue
-      fi
-
-      run_details      &&
-      satisfy_depends  &&
-      run_lget
-    )
+    if ! module_installed $MODULE || [ ! -n "$PROBE" ] ; then
+      (
+        run_details      &&
+        satisfy_depends  &&
+        run_lget
+      )
+    fi
   done
 }
 pass_two()  {
